# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: flutter github actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '1.0.0+1'
          channel: 'stable'
      - name: "Flutter Analyze"
        run: flutter analyze .
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.1'
          channel: 'stable'
      - name: "Flutter Format"
        run: flutter format . --set-exit-if-changed
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.1'
          channel: 'stable'
      - name: "Flutter Test"
        run: flutter test .
